source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'sqlite3-ruby', :require => 'sqlite3'
group :development, :test do
  gem "rspec-rails"
  gem "cucumber-rails"
  gem "webrat"
  gem "capybara"
  gem "database_cleaner"
  gem "selenium-client"
end
